name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CLI_PKG: 'vesperando_cli'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    env:
      CLI_SPEC: 'vesperando_cli.spec'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Set up Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v3

      - name: Set up Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.x

      - name: Set up Packages
        run: |
          python scripts/setup_dev.py
        working-directory: ./

      - name: Build Executable
        run: |
          pyinstaller ${{ env.CLI_SPEC }}
        working-directory: ./

      - name: Create Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CLI_PKG }}-windows
          path: dist/

      - name: Archive as tarball (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar cvf - ${{ env.CLI_PKG }} | gzip -9 - > ${{ env.CLI_PKG }}-linux.tar.gz
        working-directory: ./dist/

      - name: Create Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CLI_PKG }}-linux
          path: dist/${{ env.CLI_PKG }}-linux.tar.gz
          compression-level: 0

      - name: List bundle output
        run: ls -R ./dist/

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List Downloaded Files (Debug)
        run: |
          ls -R

      - name: Zip Windows Artifact
        run: |
          zip -r ${{ env.CLI_PKG }}-windows.zip ${{ env.CLI_PKG }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          overwrite_files: true
          files: |
            ${{ env.CLI_PKG }}-linux.tar.gz
            ${{ env.CLI_PKG }}-windows.zip